name: cd-frontend
'on':
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        required: true
      run_number:
        description: Build Number
        required: true
  workflow_run:
    workflows:
      - ci-frontend
    branches:
      - main
      - main
      - main
    paths:
      - '**/frontend/**'
    types:
      - completed
env:
  REPOSITORY_NAME: UATTest
jobs:
  set-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - if: |
          github.event.inputs.environment == '' && contains(github.event.workflow_run.head_branch, 'main')
        name: Set Dev env
        run: |-
          echo ENVIRONMENT=Dev>> $GITHUB_ENV
          echo "RUN_NUMBER=${{github.event.workflow_run.run_number}}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV
      - if: |
          github.event.inputs.environment == '' && contains(github.event.workflow_run.head_branch, 'main')
        name: Set prod env
        run: |-
          echo ENVIRONMENT=prod>> $GITHUB_ENV
          echo "RUN_NUMBER=${{github.event.workflow_run.run_number}}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV
      - if: |
          github.event.inputs.environment == '' && contains(github.event.workflow_run.head_branch, 'main')
        name: Set uat env
        run: |-
          echo ENVIRONMENT=uat>> $GITHUB_ENV
          echo "RUN_NUMBER=${{github.event.workflow_run.run_number}}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV
      - if: |
          github.event.inputs.environment == 'Dev'
        run: |
          echo ENVIRONMENT=Dev>> $GITHUB_ENV
          echo "RUN_NUMBER=${{github.event.inputs.run_number}}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
      - if: |
          github.event.inputs.environment == 'prod'
        run: |
          echo ENVIRONMENT=prod>> $GITHUB_ENV
          echo "RUN_NUMBER=${{github.event.inputs.run_number}}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
      - if: |
          github.event.inputs.environment == 'uat'
        run: |
          echo ENVIRONMENT=uat>> $GITHUB_ENV
          echo "RUN_NUMBER=${{github.event.inputs.run_number}}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: set Env
        id: setEnv
        run: |
          export ENVIRONMENT="${{ env.ENVIRONMENT }}"
          export RUN_NUMBER="${{ env.RUN_NUMBER }}"          
          export BRANCH_NAME="${{ env.BRANCH_NAME }}"          
          echo "::set-output name=environment::${ENVIRONMENT}"
          echo "::set-output name=run_number::${RUN_NUMBER}"
          echo "::set-output name=branch_name::${BRANCH_NAME}"
    outputs:
      environment: ${{ steps.setEnv.outputs.environment }}
      run_number: ${{ steps.setEnv.outputs.run_number }}
      branch_name: ${{ steps.setEnv.outputs.branch_name }}
  Dev:
    runs-on: ubuntu-latest
    needs: set-environment
    if: (needs.set-environment.outputs.environment == 'Dev' && github.event.workflow_run.conclusion != 'failure')
    environment: Dev
    steps:
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.CR_LOGIN_SERVER }}
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASSWORD }}
      - name: deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: rapidx_cms_4
          publish-profile: ${{ secrets.AZURE_RAPIDX_CMS_4_PUBLISH_PROFILE }}
          images: ${{ secrets.CR_LOGIN_SERVER }}/${{ env.REPOSITORY_NAME }}:${{needs.set-environment.outputs.run_number}}
  prod:
    runs-on: ubuntu-latest
    needs: set-environment
    if: (needs.set-environment.outputs.environment == 'prod' && github.event.workflow_run.conclusion != 'failure')
    environment: prod
    steps:
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.CR_LOGIN_SERVER }}
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASSWORD }}
      - name: deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: rapidx_cms_4
          publish-profile: ${{ secrets.AZURE_RAPIDX_CMS_4_PUBLISH_PROFILE }}
          images: ${{ secrets.CR_LOGIN_SERVER }}/${{ env.REPOSITORY_NAME }}:${{needs.set-environment.outputs.run_number}}
  uat:
    runs-on: ubuntu-latest
    needs: set-environment
    if: (needs.set-environment.outputs.environment == 'uat' && github.event.workflow_run.conclusion != 'failure')
    environment: uat
    steps:
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.CR_LOGIN_SERVER }}
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASSWORD }}
      - name: deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: reactcomp
          publish-profile: ${{ secrets.AZURE_REACTCOMP_PUBLISH_PROFILE }}
          images: ${{ secrets.CR_LOGIN_SERVER }}/${{ env.REPOSITORY_NAME }}:${{needs.set-environment.outputs.run_number}}
